name: Access AKS cluster
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get kubeconfig
        run: az aks get-credentials -g ${{ secrets.RESOURCE_GROUP_NAME }} -n ${{ secrets.AKS_NAME }}

      - name: Get kubelogin
        run: brew install Azure/kubelogin/kubelogin

      - name: Convert kubeconfig
        run: kubelogin convert-kubeconfig -l workloadidentity

      - name: Run kubectl
        env:
          AZURE_AUTHORITY_HOST: https://login.microsoftonline.com/
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          kubectl get nodes
